### ISSUE TITLE
[FEATURE] ROADMAP 2024

### ISSUE THREAD

**Issue by mlinmg** [astramind-ai/Pulsar#1]
We plan on progressing the state of the UI a lot, if yopu have suggesiton feel free to comment this issue

- [ ] Release a UI version for Mac
- [ ]  Add a general artifact (claude-like) mode
- [ ] Add the possibility to share the server locally without using the online url setting
- [ ] Add a permanent token generation system to beign able to connect to your machine from outside of your network
- [ ] add multiple RP specific samplers
- [ ] functions and extension added to the store 
- [ ] RAG
- [ ] Txt2Img (cpu based)
- [ ] Speech2Txt 
- [ ] Speech2Speech
